name: Publish

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Java 21
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: cd web && bun install
      - name: Build frontend
        run: cd web && bun run build
      - name: Build with Gradle
        run: ./gradlew jib --stacktrace
